PULP_APP = test
PULP_APP_FC_SRCS = test.c
PULP_APP_HOST_SRCS = test.c
PULP_CFLAGS = -O3 -g
#CONFIG_OPT += gvsoc/trace=dma
#CONFIG_OPT += gvsoc/trace=ddr
#CONFIG_OPT += **/board/ddr/tlm/gem5-config=config.ini
#CONFIG_OPT += **/board/ddr/tlm/dramsys-config=sim.xml
include $(PULP_SDK_HOME)/install/rules/pulp_rt.mk
